# Generated by Django 5.2.5 on 2025-11-09 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GmailCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_email', models.EmailField(max_length=254, unique=True)),
                ('token_json', models.JSONField(default=dict)),
                ('scopes', models.JSONField(blank=True, default=list)),
                ('token_expiry', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('user_email',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GmailSyncState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(default='primary', max_length=64, unique=True)),
                ('user_email', models.EmailField(blank=True, max_length=254)),
                ('history_id', models.CharField(blank=True, max_length=128)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('query', models.CharField(blank=True, max_length=500)),
                ('fetched_messages', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ('label',),
                'abstract': False,
            },
        ),
    ]
