# Generated by Django 5.2.5 on 2025-11-09 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_gmailcredential_gmailsyncstate'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='category_confidence',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='category_source',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.CreateModel(
            name='CategoryRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128)),
                ('match_value', models.CharField(blank=True, max_length=255)),
                ('match_field', models.CharField(choices=[('merchant', 'Merchant Name'), ('description', 'Description'), ('card_last4', 'Card Last4'), ('any', 'Any Text')], default='merchant', max_length=32)),
                ('match_type', models.CharField(choices=[('contains', 'Contains'), ('starts_with', 'Starts With'), ('ends_with', 'Ends With'), ('exact', 'Exact'), ('regex', 'Regex'), ('always', 'Always Match')], default='contains', max_length=32)),
                ('card_last4', models.CharField(blank=True, help_text='Optional: restrict rule to a specific card last4.', max_length=4)),
                ('min_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('max_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('priority', models.PositiveIntegerField(default=100)),
                ('confidence', models.FloatField(default=0.8)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='tracker.category')),
            ],
            options={
                'ordering': ('priority', '-confidence', 'name'),
                'abstract': False,
            },
        ),
    ]
