# Generated by Django 5.2.5 on 2025-11-09 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_transaction_category_confidence_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='llmdecisionlog',
            name='cache_key',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
    ]
