# Generated by Django 5.2.5 on 2025-11-10 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_llmdecisionlog_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='expense_account',
            field=models.CharField(blank=True, help_text='Cuenta o categoría contable asociada a esta tarjeta.', max_length=128),
        ),
    ]
