# Generated by Django 5.2.5 on 2025-11-11 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0014_transactioncorrection_subcategories'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='subcategory',
            name='unique_category_subcategory',
        ),
        migrations.AlterUniqueTogether(
            name='subcategory',
            unique_together={('category', 'code')},
        ),
    ]
