# Generated by Django 5.2.5 on 2025-11-15 00:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0020_categorysuggestion_groupmembership_spendinggroup_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportJob',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('queued', 'En cola'), ('syncing', 'Sincronizando correos'), ('processing', 'Procesando transacciones'), ('completed', 'Completado'), ('failed', 'Con errores')], default='queued', max_length=16)),
                ('range_choice', models.CharField(blank=True, max_length=16)),
                ('after_date', models.DateField(blank=True, null=True)),
                ('gmail_query', models.TextField(blank=True)),
                ('outlook_query', models.TextField(blank=True)),
                ('max_messages', models.PositiveIntegerField(default=50)),
                ('fetched_count', models.PositiveIntegerField(default=0)),
                ('processed_total', models.PositiveIntegerField(default=0)),
                ('processed_messages', models.PositiveIntegerField(default=0)),
                ('created_transactions', models.PositiveIntegerField(default=0)),
                ('error_count', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('last_progress_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
    ]
